export default {
  models: 'Models',
  modelDetails: 'Model Details',
  modelRuns: 'Models Runs',
  overview: 'Overview',
  runs: 'Runs',
  create: {
    createModels: 'Create My Model',
    modelsName: 'Models Name',
    createHolder: 'Enter name...',
  },
  list: {
    myModels: 'My Models',
    all: 'All',
    image: 'Image',
    lidar: 'LiDAR',
  },
  detail: {
    usage: 'Usage',
    creator: 'Creator',
    createTime: 'Creation Time',
    overview: 'Overview',
    runs: 'Runs',
  },
  overviewPage: {
    description: 'Description',
    scenarios: 'Scenarios',
    classes: 'Classes',
  },
  run: {
    runModel: 'Run Model',
    syncTable: 'Sync Table',
    runId: 'Run ID',
    datasetName: 'Dataset Name',
    createdAt: 'Created At',
    status: 'Status',
    progress: 'Progress',
    actions: 'Actions',
    reRun: 'Re-run',
    viewDataset: 'View Dataset',
    delete: 'Delete',
  },
  runModel: {
    dataset: 'Dataset',
    confidence: 'Confidence',
    classes: 'Classes',
    predict: 'Predict All in Model',
    selectAll: 'Select All',
    unselectAll: 'Unselect All',
    selectDataset: 'Please select the dataset first',
    selectClass: 'Please select at least one Class',
  },
  deleteModel: {
    title: 'Warning',
    text: 'Are you sure you want to delete the Model Run?',
    hasDeleted: 'Deleted',
  },
};
