export default {
  url: 'URL',
  data: 'Data',
  overview: 'Overview',
  qa: 'QA',
  architecture: 'Zip file architecture',
  architectureTip:
    'Basic Ai format:we will zip the file by our standard format  \n Same as upload: we will zip the file by your original zip architecture when you upload data.',
  parseZipByTip:
    "If you choose to select by folder name, we will parse the zip files based on folder names that contain keywords such as 'batch' and 'scene'. However, if you choose to select by architecture, the last level will be 'data', and the upper levels will be 'scene' and 'batch'. For more details, please refer to our documentation.",

  objects: 'Objects',
  dashboard: 'Dashboard',
  autoTag: 'AutoTag',
  upload: 'Upload',
  open: 'Open',
  selectItemsCount: 'items selected',
  selectAll: 'Select All',
  unSelectAll: 'Unselect All',
  assign: 'Assign',
  changeStatus: 'Change Status',
  delete: 'Delete',
  more: 'More',
  localData: 'Local Data',
  objectStorage: 'Object Storage',
  dataType: 'Data Type',
  uploadDate: 'Uploaded Date',
  addDate: 'Data Added',
  Status: 'Status',
  Resolved: 'Resolved',
  Unresolved: 'Unresolved',
  ViolationOfRules: 'Violation of rules',
  withAnyViolations: 'with Any violations',

  groundTruths: 'Ground Truths',
  annotationCount: 'Annotation Count',
  uploadLocalData: 'Upload Local Data',
  uploadPlaceholder:
    'Click to select files or drag and drop file here… Current dataset is an image dataset. zip/gzip/tar formats are supported.',
  uploadImagePlaceholder:
    'Click to select files or drag and drop files here. Supported file types: zip/gzip/tar/jpg/jpeg/png',
  uploadCancelWarning: 'You have files uploading, do you want to discard them all?',
  deleteData: 'Delete Data',
  deleteDataClassWarning:
    'Are you sure to delete the selected items or scenes? This action is irreversible.',

  uploadingItems: 'Items Uploading',
  uploadedItems: 'Uploads Complete',
  uploadData: 'Upload Data',
  cancelUpload: 'Cancel Upload',
  continueUpload: 'Continue Upload',

  terminateUpload: 'Terminate Upload',
  terminateExport: 'Terminate Export',
  terminate: 'Terminate',
  terminateUploadPlaceholder: 'Are you sure you want to terminate upload process?',
  terminateExportPlaceholder: 'Are you sure you want to terminate the export process？',

  editingBy: 'Editing By',

  process: {
    uploading: 'Uploading: ',
    exporting: 'Exporting: ',
    finished: 'Finished:',
    item: ' item',
    items: ' items',
    upload: ' upload',
    uploads: ' uploads',
    export: ' export',
    exports: ' exports',
    complete: ' complete',
    ready: ' ready',
    invalidFormat: 'Invalid Format',
  },
  creameModel: {
    History: 'History',
    Calibrate: 'Calibrate',
    title: 'Calibrating camera parameters',
    tips: 'One data will be randomly selected for parameter calibration, and the correction will be applied to all data.',
    Name: 'Name',
    CalibratedTime: 'Calibrated Time',
    Operations: 'Operations',
    Original: 'Original',
  },
  uploadModel: {
    pathPlaceholder: 'Please input path like /Directory/test.rar or test.rar',
    // 0
    and: 'and',
    uploadResult: ' how to upload data with results.',
    // 1
    uploadLocalData: 'Upload Local Data',
    clickText: 'Click to select files ',
    dragText: 'or drag and drop file here ',
    compressedFiles: 'Only compressed file (zip/gzip/tar)',
    widthText: 'with',
    formatText: ' supported 3D format ',
    widthSupported: ' are supported.',
    checkText: 'Check documentation for',
    checkImageText: 'Check documentation for supported data format ',
    supportedTypes: 'Supported file types:',
    imageTypes: 'zip/gzip/tar/jpg/jpeg/png',
    limitUploadLocal:
      'There is a file size limit of 1 GB. For larger files, URL or Object Storage uploads are recommended.',
    // 2
    uploadByUrl: 'Upload by URL',
    validUrl: 'Valid URL',
    invalidUrl: 'Invalid URL',
    supported: ': only zip file is supported',
    provide: 'Please provide the URL to help us access the compressed zip file',
    generateUrl: 'Check documentation for how to generate the URL.',
    generateText: 'Amazon guide, Azure guide and Google Cloud guide.',
    connect: 'Connect',
    finish: 'Finish',
    // 3
    minIOBucket: 'MinIO Bucket',
    uploadMinIO: '1. Please upload your zip file to our MinIO Bucket via following info:',
    specifyMinIO: '2. Please specify your path in the MinIO Bucket',
    containsResultMinIO: '3. Please specify if your data contains pre-label result',
    endPoint: 'Server:',
    accessKey: 'AccessKey:',
    secretKey: 'SecretKey:',
    path: 'Path',
    validPath: 'Valid Path',
    invalidPath: 'Invalid Path',
    tipsUse: 'You can use ',
    cyberduck: 'Cyberduck ',
    tipsOr: 'or your code to upload. For more details, please check ',
    minioGuides: 'MinIO Guides',
    containsResult: 'Contains Prelabeled Result',
    resultType: 'Result Type',
    resultName: 'Result Name',
    selectResults: 'Select Results',
    linkPlaceholder: 'Input a URL that links to your zip file',

    imageTypeError: 'You can only upload zip/gzip/tar/jpg/jpeg/png file!',
    zipTypeError: 'You can only upload zip/gzip/tar file!',
    fileSizeMax1GB: 'File must smaller than 1GB!',
    resultNameRequired: 'Result Name is required',
  },
  parse: {
    parseZip: 'Parse zip by',
    folderName: 'Folder Name',
    folderArchitecture: 'Folder Architecture',
    sceneAndData: 'Scene and data',
    justData: 'Just data',
    BatchSceneAndData: 'Batch, scene and data',
    batchAndData: 'Batch and data',
    tip: "If you choose to select by folder name, we will parse the zip files based on folder names that contain keywords such as 'batch' and 'scene'. However, if you choose to select by architecture, the last level will be 'data', and the upper levels will be 'scene' and 'batch'. For more details, please refer to our documentation.",
  },

  sort: {
    itemName: 'Item Name',
    createDate: 'Create Date',
    annotateCount: 'Annotation Count',
    updateDate: 'Update Date',
  },
  createDate: 'Create Date',
  singleData: 'Single Data',
  frame: 'Scene',
  batch: 'Batch',
  frameAction: {
    frame: 'Group a Scene',
    frameMultiple: 'Group Multiple Scenes',
    unFrame: 'Ungroup Scenes',
    merge: 'Merge into a Scene',
    moveOut: 'Remove',
  },
  modalTitle: {
    merge: 'Merge into a Scene',
    frameMultiple: 'Group Multiple Scenes',
    minio: 'MinIO Bucket',
    url: 'Upload by URL',
  },
  tips: {
    mergeTips: 'Merge current selection to',
    frameMultipleTipsBefore: 'Create a Scene every',
    frameMultipleTipsAfter: 'items',
  },

  urlError: 'Please enter a path with a zip type',

  unLock: {
    tips: 'Once you force unlock selected occupants, they are not able to change those data until you claim them again. Any unsaved changes will be discarded',
    totalSelect: 'Total selected occupied data',
    searchPlaceholder: 'Search by occupants’ name',
    forceUnlock: 'Force Unlock',
  },
  emptyTips: 'No items in this dataset yet.',

  lockedTips: 'You have occupied {dataNum} data, continue annotating？',

  export: {
    allData: 'All data',
    filterData: 'Filtered data',
    selectedData: 'Selected data',
    basicAiFormat: 'Basic AI format',
    sameAsUpload: 'Same as upload',
  },
};
