export default {
  ontology: 'Ontology',
  // 空列表
  emptyOntology: 'Empty Ontology',
  emptyClass: 'Empty Classes',
  emptyClassification: 'Empty Classification',
  // 新建 ontology
  createHolder: 'Input name…',
  maxLength: 'Character length should be no more than 256.',
  createOntology: 'Create Ontology',
  ontologyName: 'Ontology Name',
  ontologyType: 'Ontology Type',
  successCreated: 'Successfully Created',
  duplicate: 'Duplicate ontology name',
  noOntologyName: 'Please input name',
  // 删除 ontology
  deleteOntology: 'Delete Ontology',
  hasBeenDeleted: 'has been deleted',
  deletePlace: 'Enter ontology name here…',
  sure: 'Are you sure to delete ontology',
  removed: 'All class and classifications will be removed. ',
  verify: 'Please enter ontology name to do double-verification.',
  // 重命名 ontology
  renameOntology: 'Rename Ontology',
  newName: 'New Name',
  hasBeenRenamed: 'has been renamed',
  hasExist: ' already exist. Please rename.',
  Instruction: 'Instruction',
  QAOptional: 'QA Optional',
  // 搜索字段
  sort: {
    name: 'Item Name',
    creationTime: 'Created Date',
  },
  // 卡片列表
  card: {
    classesCount: 'Classes Count',
    type: 'Type',
    createdTime: 'Created Time',
  },
  modalMapError: 'Please create the class first.',
  inputType: {
    radio: 'radio',
    mutiSelection: 'mutiSelection',
    dropdown: 'dropdown',
    text: 'text',
  },
  // 弹窗内部的文字
  modal: {
    treeGraph: 'Tree Graph',
    basicInfo: 'Basic Info',
    attributeName: 'Attribute Name',
    optionName: 'Option Name',
    inputType: 'Input Type',
    required: 'Required',
    root: 'Root',
    options: 'Options',
    attributes: 'Attributes',
    duplicatedName: 'Duplicated Name',
    colonNotAllowed: ': is not allowed',
    constraints: {
      constraints: 'Constraints',
      standard: 'Standard',
      length: 'Length',
      width: 'Width',
      height: 'Height',
      points: 'Points',
      unitStandard: 'm',
      size: 'Size',
      area: 'Area',
      unitImage: 'px',
      min: 'min',
      max: 'max',
    },
    defaultHeight: 'Default Height',
    minHeight: 'Min Height',
    minPoints: 'Min Points',
    // 校验 class|classification
    nameRequired: 'Name Required',
    alreadyExits: ' already exist.',
    enterNewName: 'Please enter a new name.',
    datasetType: {
      image: 'Image',
      lidar: 'LiDAR',
      lidarBasic: 'LiDAR Basic',
      lidarFusion: 'LiDAR Fusion',
    },
    toolType: {
      boundingBox: 'BBox',
      polygon: 'Polygon',
      polyline: 'Polyline',
      keyPoint: 'Key Point',
      polygonPlus: 'Polygon(plus)',
      skeleton: 'Skeleton',
      curve: 'Curve',
      group: 'Group',
      imageCuboid: 'Cuboid',
      cuboid: 'Cuboid',
      segmentation: 'Segmentation',
      mask: 'Mask',
    },
    // 取消弹窗
    discard: 'Discard',
    discardChanges: 'Discard Changes',
    sureDiscard: 'Are you sure to discard the changes?',
    // options 校验
    optionsRequired: 'Options Required',
    optionValid: 'Are you sure to discard the changes?',
    optionValidFilled: 'Required fields have not been all filled. ',
    optionValidDiscard: "Are you sure to discard this attribute and it's options?",
    // 标准框校验信息
    standardValidateMax: 'Max should be larger than min',
    standardValidateMin: 'Min should be smaller than max',
    sizeLimit: {
      sizeLimit: 'Size Limit',
      lengthLimit: 'Length limit',
      widthLimit: 'Width limit',
      areaLimit: 'Area limit',
    },
    advancedConfiguration: 'Advanced Configuration',
    manageAttributes: 'Manage Attributes',
    numberOfPolygonPoints: 'Number of polygon sides',
    lidar: {
      resultType: 'Result Type',
      instance: 'Instance',
      semantic: 'Semantic',
    },
    skeleton: {
      option1: 'Left click to add points.',
      option2: 'Select and drag to change location.',
      option3:
        'Press the shift key and click the source and target point to create a connection line.',
      option4: 'Back key to delete point or line.',
      updatePicture: 'Update Picture',
      keyPointsLabel: 'Keypoints Label:',
      order: 'Order',
      label: 'Label',
      enterALabel: 'Enter a label',
      labelRepeat: 'Repeated label',
      equidistantSkeleton: 'Equidistant Skeleton',
      inOrder: 'In Order',
      custom: 'Custom',
      skeletonAttributeConfiguration: 'Skeleton Attribute Configuration',
      attribute: 'Attribute',
      hotKey: 'Hotkey',
      common: 'Common',
      outside: 'Outside',
      cover: 'Cover',
      oneOrNone: '1 OR none',
      enterATag: 'Enter a tag',
      tagRepeat: 'repeat tag',
      addConfiguration: 'Add Configuration',
      skeletonInfo: 'Skeleton class has at least one keypoint',
    },
    alias: 'Alias',
    attributeAlias: 'Attributes Alias',
    optionAlias: 'Option Alias',
    classID: 'Class ID',
    classificationID: 'Classification ID',
    copied: 'Copied',
  },
  // 搜索表单
  searchForm: {
    search: 'Search',
    searchItems: 'Search items by name…',
    sort: 'Sort',
    filter: 'Filter',
    createdDate: 'Created Date',
    datasetType: 'Dataset type',
    toolType: 'Tool type',
    activities: 'Activities',
  },
  // 复制
  copy: {
    copyEntireOntology: 'Copy Entire Ontology',
    copyFromOntology: 'Copy From Ontology Center',
    copyFrom: 'Copy From',
    next: 'Next',
    inputToSearch: 'Input to search',
    copyClass: 'Copy Class from Ontology Center',
    copyClassification: 'Copy Classification from Ontology Center',
    copyPlaceholder: 'There is no ontology of this dataset type available. You can go to ',
    copyOntologyCenter: 'Ontology Center ',
    copyToCreate: 'to create a new one.',
  },
  sync: {
    saveToOntology: 'Save to Ontology Center',
    selectOntology: 'Select an ontology to save into',
    noOntology: 'There is no ontology of this dataset type available. Please create a new one.',
    createAndSync: 'Create And Sync',
    successCreated: 'Successfully created and synchronized',
    classConflictTip:
      'Some Classes have already existed in Destination ontology. To resolve these conflicts, please choose to Keep Destination or to Replace Destination with New Classes.',
    classificationConflictTip:
      'Some Classifications have already existed in Destination ontology. To resolve these conflicts, please choose to Keep Destination or to Replace Destination with New Classifications.',
  },
  conflict: {
    tips1:
      ' Some Classes/ Classifications have already existed in your ontology. To resolve these conflicts, please choose to',
    keep: 'Keep',
    original: 'Original or to',
    replace: 'Replace',
    originalNew: 'Original with New Classes/ Classifications.',
    replaceAll: 'Replace All',
    keepAll: 'Keep All',
    noConflict: 'No Conflict',
    className: 'Class Name',
    classificationName: 'Classifications Name',
    copied: 'Copied',
    classesAnd: 'Class(es) and',
    classes: 'Class(es)',
    classifications: ' Classification(s)',
    resolution: 'Resolution',
    conflicts: 'Conflicts',
  },
  import: {
    importByJson: 'Import by Json',
    exportAsJson: 'Export as Json',
    importClassesByJson: 'Import Class/Classifications by JSON',
    tip: 'Click to select file or drag and drop file here',
    supported: 'Supported file type: Json',
    download: 'Download JSON Template',
    view: 'View Help Document',
    uploadJson: 'You can only upload json file!',
  },
  model: {
    modelMap: 'Model Map',
    model: 'Model',
    modelClasses: 'Model Classes',
    classDetail: 'Class Detail',
    discardChange: 'Discard Change',
    sureToDiscard: 'Are you sure to discard the changes?',
    modelMapError: 'please select a class',
  },
};
