export default {
  role: 'Role',
  roles: 'Roles',
  count: 'Count',
  roleType: 'Role Type',
  des: 'Create, edit, and manage roles in your organization. You can create a role based on an existing role or role template by enabling or disabling privileges as needed.',
  searchRole: 'Search for role name',
  default: 'Default',
  customize: 'Customize',
  create: {
    createRole: 'Create Role',
    editRole: 'Edit Role',
    roleName: 'Role Name',
    duplicate: 'Duplicate role name',
    description: 'Description',
    rolePrivileges: 'Role Privileges',
    expandAll: 'Expand all',
    collapseAll: 'Collapse all',
    import: 'Import',
    importFrom: 'Import',
    importRole: 'Import from existing role',
    selected: 'selected',
    enableAll: 'Enable All',
  },
  delete: {
    deleteRole: 'Delete Role',
    want: 'Want to Delete Role ',
    deleted: 'All data regarding this role will be deleted.',
  },
  privileges: {
    view: 'View',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    export: 'Export',
    annotate: 'Annotate',
    invite: 'Invite',
    remove: 'Remove',
    manage: 'Manage',
  },
  function: {
    functionPrivileges: 'Function privileges',
    dataset: {
      dataset: 'Dataset',
      viewDesc:
        'Allow members to view all types of datasets, their data and ontologies (classes & classifications) .',
      createDesc:
        'Allow members to create all types of dataset, upload data and create ontology(classes & classifications).',
      editDesc:
        'Allow members to rename datasets and to modify data and ontology inside a dataset. The privileges of data modification include uploading data, grouping scenes, ungrouping scenes, merging data to scenes.',
      exportDesc: 'Allow members to export raw data and annotation results.',
      deleteDesc:
        'Allow members to delete datasets, their data and ontologies (classes & classifications).',
      annotateDesc: 'Allow members to annotate data.',
    },
    ontologyCenter: {
      ontologyCenter: 'Ontology Center',
      viewDesc: 'Allow members to view ontologies and copy ontologies from datasets.',
      createDesc: 'Allow members to create ontologies.',
      editDesc: 'Allow members to edit ontologies and save them from datasets to ontology center.',
      deleteDesc: 'Allow members to delete ontologies.',
    },
    model: {
      modelRun: 'Model Run',
      modelRunDesc: 'Allow members to run all BasicAI built-in models in datasets.',
      modelTool: 'Model-assisted Tool',
      modelToolDesc: 'Allow member to run all Basic AI build-in models in annotation tools',
    },
  },
  admin: {
    administrativePrivileges: 'Administrative privileges',
    member: {
      member: 'Member',
      viewDesc: 'Allow members to view all members in this team.',
      inviteDesc: 'Allow members to invite other members to this team.',
      removeDesc:
        'Allow members to remove existing members and cancel invitation for pending members.',
      manageDesc: 'Allow members to manage team members, including tagging members.',
    },
    groups: {
      groups: 'Groups',
      viewAll: 'View All',
      viewAllDesc: 'Allow members to view all groups in this team.',
      createDesc: 'Allow members to create groups in this team.',
      addMembers: 'Add members in all groups.',
      addMembersDesc: 'Allow members to add members in all groups.',
      removeMembers: 'Remove Members in all groups',
      removeMembersDesc: 'Allow members to remove members in all groups.',
      disband: 'Disband all groups',
      disbandDesc: 'Allow member to disband all groups.',
    },
    roles: {
      roles: 'Roles',
      viewDesc: 'Allow members to view roles.',
      createDesc: 'Allow members to create roles.',
      assignRole: 'Assign Role',
      assignRoleDesc: 'Allow members to assign roles to other members',
      editDesc: 'Allow members to edit customized roles.',
      deleteDesc: 'Allow members to delete customized roles.',
    },
  },
};
