export default {
  taskText: 'Task',
  annotate: 'Annotation',
  review: 'Review',
  acceptance: 'Acceptance',
  addStage: 'Add Stage',
  selectClassTitle: 'Select Classes and Classifications',
  selected: 'Selected',
  clearAll: 'Clear All',
  addAll: 'Add All',
  createTask: 'Create Task',
  closeTask: 'Close Task',
  saveChange: 'Save Change',
  instruction: 'Instruction',

  manageClass: 'Manage Class',
  searchClassPlaceholder: 'Search classes and classification name',
  closed: 'Closed',
  viewPerformance: 'View Performance',
  personalPerformance: 'Personal Performance',
  myTasksPerformance: 'My Team Tasks Performance',
  annotateAll: 'Annotate All',
  reviewAll: 'Review All',
  previewAnnotationObjects: 'Preview annotation objects',
  Worker: 'Worker',
  progressStatus: {
    continue: 'Continue',
    publish: 'Publishing',
    configuring: 'Configuring',
    ongoing: 'Ongoing',
    paused: 'Paused',
    closed: 'Closed',
    completed: 'Completed',
    deleted: 'Deleted',
  },
  detail: {
    viewAllInStudio: 'View all in Studio',
    viewAllInACC: 'View all in ACC',
    viewAllInQA: 'View all in QA',
    checked: 'Checked',
    unChecked: 'UnChecked',
    accept: 'Accept',
    reject: 'Reject',
    reassign: 'Reassign',
    removeFromTask: 'Remove from Task',
    acceptAll: 'Accept All',
    rejectAll: 'Reject All',
    deleteTitle: 'Are you sure you want to delete this sample result',
    deleteDesc: 'Delete a sample result will NOT effect origin data and annotations',
    acceptAllModalTips1: 'You are going to accept',
    acceptAllModalTips2: 'You are going to accept ALL the data which compelete workflow',
    acceptAllModalTips3: 'Once you confirm this operation',
    acceptAllModalTips4: 'All members will no longer be able to modify those data in this task',
    acceptAllModalTips5: 'You can see and manage your annotation results as',
    acceptAllModalTips6: 'I understand above consequences, and want to accept those data',
    acceptAllModalPlaceHolder: 'Type text above to accept selected data',
    rejectAllModalTips1: 'You are going to Reject',
    rejectAllModalTips2: 'selected data which complete workflow',
    rejectAllModalTips3: 'You are going to reject ALL the data which compelete workflow',
    rejectAllModalTips4: 'Please select which stage you want to reject to',
    rejectAllModalTips5:
      'Only the data in the need acceptance stage will be included the data submit to acceptance stage after timestamp will not be included.',
    rejectAllModalTips6:
      'I understand this action will reject all data in the task and want to reject those data',
    rejectAllModalTips7:
      'I understand this action will reject {num} selected data and want to reject them',
    rejectAllModalPlaceHolder: 'Type text above to reject selected data',
    targetStage: 'Target Stage',
    rejectReasons: 'Reject Reasons',
    newWorker: 'New Worker',
    originalWorker: 'Original Worker',
    reassignModalTips1: 'Please select who you want to work on selected data',
    reassignModalTips2: 'Discard ground truths by original Annotator',
    samplePopover: 'only data in Need Acc stage can be sampled',
    sampleModalTips1: 'Include data in other samples',
    sampleModalTips2: 'Sampling inside a Scene',
    samplingSize: 'Sampling Size',
    and: 'and',
    framesPerSegment: 'Frames per Segment',
    randomSampling: 'Random Sampling',
    fieldWarning: 'Fields marked with * cannot be modified once the task is published.',
    preview: 'Preview',
    ViewInQA: 'View in QA',
    ViewInACC: 'View in ACC',
    ViewInStudio: 'View in QA',
    empty: "You currently don't have any data available",
  },
  create: {
    name: 'Task Name',
    createByYourself: 'Create Task by Yourself',
    createByTemplate: 'Create Task by Templates',
    dataType: 'Data Type',
    dataTypeDesc:
      'Data type defines your task data type, you can pick only one data type between LiDAR Basic, LiDAR Fusion, and image',
    scenarioType: 'Scenario Type',
    scenarioTypeDesc:
      'Scenario Type defines how you would like to organize data in this Task, Single Data is design for detection task only, while Scene supports tracking tasks',
    annotationType: 'Annotation Type',
    annotationTypeDesc:
      'Annotation Type defines how you would like to annotate your data. Instance means annotate data in instantial way like bounding box, cuboid, polygon, etc. Segmentation will be supported soon',
    industry: 'Industry',
    nameHolder: 'Please enter the name',
    taskNameLengthError: 'Task Name Character length should be no more than 100',
    uploadAttachment: 'Upload Attachment',
    onlySupports: 'Only supports PDF',
    editInstruction: 'Edit Instruction',
    next: 'Next',
    cancel: 'Cancel',
    prev: 'Prev',
    saveAndExit: 'Save and Exit',
    save: 'Save',
    thisIs: 'This is a',
    only: 'only',
    datasetWillBeShown: 'dataset will be shown',
    useTemplate: 'use template',
    pleaseSelectAData: 'Please Select a Dataset',
    selectAResult: 'Select a Result',
    cancelOrClearAll: 'Cancel/Clear All',
    regroupSceneForWorkers: 'Regroup Scene for workers',
    every: 'Every',
    dataAsaScene: 'data as a Scene',
    regroupPopover:
      'This will only effect this task, all your scene in dataset will not be modified',
    addTips: 'Please add some data to this task from',
    addTipsEnd: 'dataset',
    ontologyOf: 'Ontology of {datasetName}',
    onlyOntologyIn: 'You can only choose or edit ontology from {datasetName}',
    clickToBack: 'Click to back to change Dataset',
    preview: 'Preview in Tool',
    assignMemberTitle: 'Assign this task to Team Members',
    assignTaskAdminTitle: 'Assign Admins',
    assignTaskAdminPopover: 'Admins can manage the task.',
    assignWorkerAdminTitle: 'Assign Inspector',
    assignWorkerAdminPopover: 'Inspectors can accept the task.',
    batchSize: 'Batch Size',
    batchSizePopover: 'The number of data that each worker can claim at a time in a single stage.',
    batchSizeRequiredError: 'Please input batch size',
    maxDataDuration: 'Max Data Duration',
    maxDataDurationPopover: 'The max number of minutes for finishing a batch of data.',
    maxDataDurationRequiredError: 'Please input max batch duration',
    minutes: 'Minutes',
    dataAccuracy: 'Data Accuracy',
    dataAccuracyPopover: 'It is object accuracy threshold to determine if a data is accurate.',
    dataAccuracyRequiredError: 'Please input Data Accuracy',
    allowWorkerView: 'Allow worker to view submitted data',
    allowSame: 'Allow the same worker to work on the same data in different stages',
    searchAndFilter: 'Search & Filter',
    searchUserPlaceholder: 'Search users',
    allMembers: 'All Members',
    // leaveWarning: 'Leaving now will discard all unsaved changes. Areyou sure to leave?',
    leaveWarning: 'Are you Confirm?',
    removeUploadDataWarning: 'Are you sure you want to remove selected data?',

    selectAllError: 'Please first uncheck Select all data (filter applied)',
    nextConfirm:
      'You current task basic setting will remove all  settings in following steps, continue?',
    selectTemplate: 'Please select a template',

    publishSuccess: 'Task published',

    allowExceedArea: 'Whether to allow the result to exceed the image area',
    allowExceedClassLimit: 'Whether to allow submission if the result exceeds the class limit',

    annotationTypeHolder: 'Please select annotationType',

    addDataProgress: 'Adding data in progress...',
    addDataSuccess: 'Add data successfully, we will remove duplicates for you later',
    addStep: {
      selectAllDataApplyFilter: 'Select all data apply filter',
      uploadDataInDataset: 'Upload data in dataset',
      singleInfo: 'This is a Single Frame Task，only Single Frame data will be shown',
      trackingInfo: 'This is a Tracking Task, only Scene data will be shown',
    },
  },
  createTips: {
    taskAdminAssignTip: 'At least 1 Admin should be assigned!',
    workerAdminAssignTip: 'At least 1 Inspector should be assigned!',
    memberSelectedTip: 'At least 1 member should be selected',
    panelMaxLengthTip: 'panel name max length is 100',
    batchSizeRequired: 'Batch Size is required',
    batchSizeMax: 'Batch Size maximum is 1000',
    maxDurationRequired: 'Max Data Duration is required',
    instanceAccuracyRequired: 'Instance Data Accuracy is required',
    segmentationAccuracyRequired: 'Segmentation Data Accuracy is required',
    instanceMax: 'Instance DataAccuracy maximum is 100',
    segmentationMax: 'Segmentation DataAccuracy maximum is 100',
    publishFailed: 'task publish failed',
    reviewStageMax: 'Review stage is maximum 5',
    uncheckFilter: 'Please uncheck select all data apply filter first',
    selectItem: 'Please select a Item',
    noDataCanSelected: 'no data can be selected',
    upload10Files: 'You can only upload 10 files at most!',
    uploadPdf: 'You can only upload PDF files',
    changeDatasetTip:
      'You are currently changing dataset, which will remove all previous data selections and settings in following steps, continue？',
    selectDataset: 'Please select a dataset',
    addData: 'Please add some data',
    createDataset: 'Please create some dataset',
    addDataToTemplate: 'Please add some data to task from this {dataset}',
  },
  error: {
    classRequired: 'Please select a class or classification',
    previewError: "Can't find any data in your task, please check your task and dataset",
  },
  step: {
    taskBasics: 'Task Basics',
    uploadData: 'Upload Data',
    ontology: 'Ontology',
    instruction: 'Instruction',
    workflow: 'Workflow',
    QaOptional: 'QA Optional',
  },
  setting: {
    classTips:
      'The changes on Ontology will not automatically apply to data that have been annotated. Completed data should be fixed by hand.',
    restartModalTips1: 'You are going to Close',
    restartModalTips2: 'Once you confirm this operation',
    restartModalTips3: 'This task will NOT be able to restart',
    restartModalTips4: 'All unaccepted annotations will be discard',
  },
  list: {
    // tab
    myTask: 'My Tasks',
    taskManagement: 'Team Task Management',
    // table
    id: 'ID',
    name: 'Name',
    type: 'Type',
    taskType: 'Task Type',
    stage: 'Stage',
    stageType: 'Stage Type',
    admins: 'Admins',
    progress: 'Progress',
    ongoingData: 'Ongoing Data',
    // btn
    viewHistory: 'View History',
    annotate: 'Annotate',
    review: 'Review',
    config: 'Config',
    pause: 'Pause',
    continue: 'Continue',
    close: 'Close',
    delete: 'Delete',
    restart: 'Restart',
    // tips
    inReview: 'In Review',
    claimed: 'Claimed',
    toBeModified: 'To Be Modified',
    needAcceptance: 'Need Acceptance',
    completed: 'Completed',
    taskPool: 'Task Pool',
    // empty
    emptyText: "You don't have assigned tasks for now.",
    // search
    searchText: 'Search id or name',
  },
  listModal: {
    copySuccessfully: 'Task {name} copied successfully',
    warning: 'Warning',
    goingTo: 'You are going to ',
    confirmOption: 'Once you confirm this operation:',
    pauseTip: 'All your workers will be unable to access this task until you restart it',
    closeTip1: 'This task will NOT be able to restart',
    closeTip2: 'All unaccepted annotations will be discard',
    closeBtn2: 'Close Anyway',
    closeBtn3: 'Go To Accept',
    deleteToast: 'You need to close this task at first',
    deleteTip1:
      'All your data related to this data like comments, rejects, statistics, etc will be removed',
    deleteTip2: 'Your original data will NOT be removed',
    deleteTip3: 'All the annotations have been accepted will NOT be removed',
  },
  detailTab: {
    overview: 'Overview',
    data: 'Data',
    performance: 'Performance',
    setting: 'Setting',
  },
  welcome: {
    hello: 'Hello',
    toDoInfo:
      'In the "To-do" section, where your assigned tasks are located, simply click on "Annotate" or "Review" to begin.',
    myTaskInfo: 'And task admins can track and manage assigned tasks in the My Tasks Management',
    desc1:
      'You can find your assigned tasks in the "TODO" tab. To start, click on "Annotate/Review".',
    desc2: 'Admins can find tasks in the "My Tasks Management" tab.',
    desc3: 'Thank you for collaborating with us and helping advance AI. ',
  },
  overview: {
    statistic: {
      completed: 'Completed',
      needAcc: 'Need ACC',
      inLastDay: 'In last day',
      rejects: 'Rejects',
      comments: 'Comments',
    },
    changeTip:
      'You are viewing this task as an annotator or reviewer. In this view, dashboard only shows data related to you . Click here to work as admin in this task',
    changeBtnText: 'View as Admin',
    changeTipForInspector:
      'You are viewing this task as an annotator or reviewer. In this view, dashboard only shows data related to you . Click here to work as inspector in this task.',
    changeBtnTextForInspector: 'View as Inspector',
    progress: 'Progress',
    progressCompleted: 'Completed',
    accuracy: 'Accuracy',
    accuracyTip: 'Accuracy monitors your annotation accuracy in this task by data and objects',
    byData: 'By Data',
    byObjects: 'By Objects',
    segmentAccuracyTip:
      'Accuracy monitors your annotation accuracy in this task by data and points',
    byPoint: 'By Points',
    stage: 'Stage breakdown',
    stageTip: 'Stage breakdown display how your data is distributed in every stage',
    empty: 'No Instruction',
    progressEmpty: "You don't have assigned tasks for now.",
    notStarted: 'Not Started',
    object: 'Object',
    notClaimed: 'Not Claimed',
    working: 'Working',
    submitted: 'Submitted',
    rejected: 'Rejected',
    segmentationPoint: 'Segmentation Point',
    segmentationData: 'Segmentation Data',
    segmentationObject: 'Segmentation Object',
    imgCardAccuracy: {
      IObject: 'I-Object',
      SPoint: 'S-Point',
      SObject: 'S-Object',
    },
  },
  countdown: {
    claim: 'Claim',
    emptyClaim: "You currently don't have any data available",
    emptyTip:
      'You can claim up to {dataNum} data at once, with a batch duration of {minute} minutes. Therefore, you have a maximum of {perMinute} minutes per data.',
    emptyNoData: 'No Data left, congratulation!',
    openWarning: 'Claimed data has expired. Please claim again.',
    pausedFor: 'Paused for',
    dueIn: 'Due in',
    activeSelect: {
      withComments: 'With Comments',
      withMyComments: 'With My Comments',
      withWorkflowRejects: 'With Workflow Rejects',
    },
    actionList: {
      submit: 'Submit',
      pass: 'Pass',
      reject: 'Reject',
      annotate: 'Annotate',
      review: 'Review',
      markValid: 'Mark as Invalid',
    },
    expiringModal: {
      claimedData: 'Your claimed data (',
      isExpiring: ' data remaining) is expiring in ',
      release: 'After that, they will all be released to task pool.',
    },
    expiredModal: {
      refresh: 'Please refresh to claim again.',
      claim: 'Claimed data has expired. Click to claim again.',
    },
    pauseModal: {
      claim: 'Claimed data is now paused. Click restart to start working again.',
    },
    submitModal: {
      submit: 'Submit',
      goingTo: 'You are going to submit selected ',
      data: 'data',
      confirmOption: 'Once you confirm this operation:',
      tip1: 'Those data will be submit to next stage of the queue',
      tip2: 'You are not able to modify this data until Task manager or worker in next stage send them back to you',
      endText: 'I understand above consequences, and want to submit those data',
    },
    rejectModal: {
      reject: 'Reject',
      goingTo: 'You are going to reject selected ',
      data: 'data',
      targetStage: 'Target Stage',
      worker: 'Worker',
      original: 'Original',
      originalTip: 'Who submitted this work',
      new: 'New',
      newTip: 'Assign to any other worker in the stage',
      result: 'Result',
      keepResults: 'Keep results',
      keepResultsTip1: 'Keep all results and performances',
      clearResults: 'Clear results',
      clearResultsTip2: 'Clear all ground truth results',
      rejectReasons: 'Reject Reasons',
    },
  },

  taskList: {
    TodoTab: 'To-do',
    myTaskManagementTab: 'My Task Management',
  },

  taskDetail: {
    previewTips: 'Preview annotation objects',
    settingAlert: 'To make changes in this Task, you have to assign yourself as Task Admin first.',
    dataAlertBefore: 'To do actions in this task, you have to assign yourself as Task Admin in',
    dataAlertAfter: 'tab first',
    dataAdded: 'Data Added',
    dataStatus: 'Data Status',
    workflowStatus: 'Workflow Status',
    AssigneeAnnotator: 'Assignee Annotator',
    Activities: 'Activities',
    sampling: 'Sampling',
    acceptTask: 'Accept Task',
    rejectTask: 'Reject Task',
    byObject: 'by Object',
    byData: 'by Data',
    byPoint: 'by Point',
    withComments: 'With Comments',
    withMyComments: 'With My Comments',
    markedAsInvalid: 'Marked as Invalid',
    withWorkflowRejects: 'With Workflow Rejects',
    withACCRejects: 'With ACC Rejects',
    pausedForAnHour: 'Paused for an hour',
    sample: {
      accuracyIn: 'Accuracy in',
      sample: 'Sample',
      all: 'All',
      details: 'Details',
      samplingMethod: 'Sampling Method',
      samplingTotalSize: 'Sampling/Total Size',
      samplingBy: 'Sampling by',
      samplingDate: 'Sampling Date',
      samplingTip: 'You can sampling Scene in review mode in tool',
      samplingData: 'Sampling Data',
      totalSize: 'Total size(Apply Current Filters)',
      fileSize: 'files（{ totalPercent }% of total）',
    },
    ifChecked: 'If Checked',
    stageStatus: 'Stage Status',
    workingByOthers: 'Working by others',
    lock: {
      occupiedBy: 'Occupied by',
      occupiedDataCount: 'Occupied Data Count',
      selectRecord: 'please select a record',
    },
    addDataSuccessfully: 'Add data successfully',
    remove: {
      removeData:
        "You are going to remove {num} data from the task. Once removed, they'll no longer be worked in the task.",
      removeSuccess: '{num} data removed from the task.',
      removeFailure: "{num} failed, because they're already claimed.",
    },
  },
  taskSetting: {
    linkedDataset: 'Linked Dataset',
    annotationType: 'Annotation Type',
    taskStarted: 'Task Started',
    taskCompleted: 'Task Completed',
    viewInNewTab: 'View In New Tab',
  },
};
