export default {
  team: 'Team',
  addMember: 'Add Members',
  invite: 'Invite',
  changeRole: 'Change Role',
  transferRole: 'Transfer Role',
  removeMember: 'Remove Team Member',
  removeConfirmText: 'Are you sure to remove team member',
  teamMember: 'Members',
  transfer: 'Transfer',
  applicant: 'Applicant',
  joinRequest: 'Member Joining Request',
  transferTip:
    'Once you’ve transfered team owner role to other member. Your account will be set to other role.',
  transferUserLabel: 'Transfer team owner role to',
  resetRoleLabel: 'Reset my role as',
  canelInviteBtn: 'Cancel Invitation',
  teamInfo: 'Team Info',
  pendingMembers: 'Pending Members',
  disbandTeam: 'Disband Team',
  createTeam: 'Create a Team',
  joinTeam: 'Join a Team',
  action: 'Action',
  actionList: {
    accept: 'Accept',
    reject: 'Reject',
  },

  tab: {
    member: 'Members',
    group: 'Groups',
    role: 'Roles',
    setting: 'Setting',
    planBilling: 'Plan & billing',
  },

  setting: {
    dangerZone: 'Danger Zone',
    transfer: 'Transfer',
    transferOwnership: 'Transfer Ownership',
    transferOwnershipDesc: 'Transfer this team to another user.',
    disbandTeam: 'Disband this team',
    disbandTeamDesc:
      'Once you disband a team, all data about this team will be deleted permanently.',
    sureDelete: 'Are you sure you want to disband the {name}',
    removed: 'You can’t undo this action, all files, data and team members will be removed',
    type: ' Please type “{name}” to confirm ',
  },
  members: {
    manageUserRole: 'Manage User Roles',
    acceptSelected: 'Accept Selected',
    rejectSelected: 'Reject Selected',
    viewAll: 'View All',
    members: 'Members',
    inviteMember: 'Invite Member',
    selected: 'Selected',
    users: 'Users',
    tag: 'Tag',
    tags: 'Tags',
    createTag: 'Create Tag',
    category: 'Category',
    createCategory: 'Create Category',
    manageTags: 'Manage Tags',
    more: 'More',
    assign: 'Assign',
    assignTags: 'Assign Tags',
    assignGroup: 'Assign Groups',
    assignToGroup: 'Assign to Groups',
    assignRole: 'Assign Role',
    manageRole: 'Manage Role',
    permissions: 'Permissions',
    removeFromTeam: 'Remove from Team',
    cancelInvite: 'Cancel Invitation',
    importTitle: 'Import members by Excel',
    emptyTags: 'Please go to the member page to add a tag',
    deleteTag1: 'Are you sure you want to delete label ',
    deleteTag2: 'Deleting a label will remove it from all members',
    deleteCategory1: 'Are you sure you want to delete category ',
    deleteCategory2:
      ' Deleting a category will remove all its tags and remove all tags from all members',
    active: 'Active',
    pending: 'Pending',
    cancel: 'Are you sure you want to cancel those member?',
    remove: 'Are you sure you want to remove those members',
    pleaseSelectMembers: 'Please select members',
  },
  group: {
    owner: 'Owner',
    uploadTip: 'You can only upload jpg/jpeg/png file!',
    smaller: 'file must smaller than 20MB!',
    addSuccess: 'Add member to group successfully',
    pleaseSelectMember: 'Please select member',
    changeNameSuccess: 'Change group name successfully',
    changeDescriptionSuccess: 'Change group description successfully',
    removeSuccess: 'Remove member from group successfully',
    deleteSuccess: 'Delete group successfully',
  },
  role: {
    privilegesCannotBeEmpty: 'Privileges cannot be empty',
    editRoleSuccessfully: 'Edit role successfully',
    createRoleSuccessfully: 'Create role successfully',
    deleteRoleSuccessfully: 'Delete role successfully',
  },
  assign: {
    tagsWithoutCategory: 'Tags without category',
    assignGroupToMember: 'Assign group to member successfully',
    assignGroupToMembers: 'Assign group to {number} members successfully',
    assignTagToMember: 'Assign tag to member successfully',
    assignTagToMembers: 'Assign tag to {number} members successfully',
    assignRoleToMember: 'Assign role to member successfully',
    assignRoleToMembers: 'Assign role to {number} members successfully',
  },
  form: {
    emailCanNotBeNull: 'Email can not be empty',
    accountCanNotBeNull: 'Account can not be empty',
    pleaseEnterAValidEmail: 'Please enter a valid email',
    roleCanNotBeNull: 'Role can not be empty',
  },
  import: {
    or: 'Or',
    importByExcel: 'Import By Excel',
    drag: 'Drag & drop files or',
    browse: 'Browse',
    supported:
      'Supported formats: xls, xlsx. “Email” and “Role” field is required in your file, and Role field must be one of your role list.',
    invitation: '100 members is limited for one invitation',
    uploadSuccess: 'Uploaded successfully',
    download: 'Click to download the excel template',
    errorTip: 'You can only upload xls/xlsx file!',
  },
  teamExpire: {
    expireTitle: 'Team Expiration Reminder',
    disableTitle: 'Team Disablement Reminder',
    expireTips:
      'The package for team { teamName } has expired. To continue using, please contact customer service.',
    disableTips:
      'Team { teamName } has been disabled. To continue using, please contact customer service.',
    switchTeam: 'Switch Team',
  },
  billing: {
    billingExpireTip: 'Your team has completed the unsubscription and will expire on the { date }',
    currentPlan: 'Current Plan',
    expiresOn: 'Expires on { date }',
    expiredOn: 'Expired on { date }',
    month: '/Month',
    quarter: '/Quarter',
    halfYear: '/Half year',
    year: '/Year',
    perMonth: 'Per Month',
    perQuarter: 'Per Quarter',
    perHalfYear: 'Per Half Year',
    perYear: 'Per Year',
    additionalModelCalls: 'Additional Model Calls',
    paymentProcessing: 'Payment Processing',
    subscriptionAgreement: 'Subscription Agreement',
    billingForm: {
      select: 'Select',
      monthly: 'Monthly',
      quarterly: 'Quarterly',
      semiAnnual: 'Semi-annual',
      annual: 'Annual',
      yearly: 'Yearly',
      members: 'Members',
      storage: 'Storage',
      storageSpace: 'Storage space',
      modelCalls: 'Model calls',
      modelCallsTip:
        'The current team has { member } members and { storage }GB of data. Please reduce your team members and storage data under the downgrade plan before the next cycle.',
      additional: 'Additional',
    },
    unsubscribeModal: {
      unsubscribe: 'Unsubscribe',
      unsubscription: 'Unsubscription',
      sureUnsubscribe: 'Are you sure you want to unsubscribe from BasicAI?',
      unsubscribeTips:
        "Confirmation to unsubscribe will take effect immediately, and you will not be able to access your team's functions after the current payment cycle.",
    },
    subscribeModal: {
      subscribe: 'Subscribe',
      subscribeToAPlan: 'Subscribe to a plan',
      teamPlan: 'Team plan',
      enterprisePlan: 'Enterprise Plan',
      newPlan: 'New Plan',
      off: '{ discount } OFF',
      enterpriseTip:
        'You can contact us immediately to customize the payment cycle, number of members, storage space and number of model calls, and get an exclusive plan for your company.',
      planList: {
        dataManagement: 'Data management',
        modelsManagement: 'Models Management',
        taskManagement: 'Task management',
        ontologyManagement: 'Ontology Management',
        image: 'Image & image frame tool',
        Lidar: 'LiDAR + LiDAR Fusion & LiDAR frame tool',
        organizationManagement: 'Organization management',
        custom: 'Custom Members, Stores, and Model Calls',
        dedicated: 'Dedicated customer operations support',
      },
      result: {
        paymentSuccess: 'Payment Successfully',
        subscriptionSuccess: 'Subscription Successfully',
        successTip1: 'Thank you for your business with us!',
        successTip2: 'Start your efficient annotation and deploy.',
        getStarted: 'Get Started',
        paymentFailed: 'Payment Failed',
        failedTip1: 'The payment was unsuccessful due to an abnormality.',
        failedTip2: 'Please try again later or use another payment method.',
        tryAgain: 'Try Again',
      },
      validInfo: '*Valid for 1 month from the delivery date',
    },
    gradeModal: {
      upgrade: 'Upgrade',
      upgradeTip1: "*This team's plan will be upgraded.",
      upgradeTip2:
        'It will take effect immediately this month of the current plan, and next month will automatically subscribe to the new upgrade plan.',
      upgradeTip3:
        'The payment amount for this upgrade may be prorated, as appropriate, based on the billing cycle for selected plans.',
      downgrade: 'Downgrade',
      downgradeTip1: "*This team's plan will be downgraded.",
      downgradeTip2:
        'It will take effect in next month and automatically subscribe to the new downgrade plan.',

      prorated:
        '*The estimated total may be prorated, as appropriate, based on the billing cycle for selected plans.',
      sureDowngrade: 'Are you sure you want to downgrade the team plan?',
      original: 'Original',
      current: 'Current',
      teamPlan: 'Team Plan (5members, 200GB storage)',
    },
    modelCallsModal: {
      append: 'Append',
      addModelCalls: 'Add model calls',
      modelCallsTip: 'Used this month/ Usage remaining this month (Total)',
    },
    resumeModal: {
      resume: 'Resume',
      sureResume: 'Are you sure you want to resume the subscription?',
    },
    billingTable: {
      billingInvoice: 'Billing & Invoice',
      billingID: 'Billing ID',
      invoiceID: 'Invoice ID',
      service: 'Service',
      paymentPeriod: 'Payment Period',
      amountPaid: 'Amount Paid',
      paidOn: 'Paid On',
      paymentMethod: 'Payment Method',
      status: 'Status',
      paid: 'Paid',
      failed: 'Failed',
      refunded: 'Refunded',
      pending: 'Pending',
    },
    billingCard: {
      upcomingBilling: 'Upcoming Billing',
      total: 'Total',
      autoPayOn: 'Autopay on {date}',
      newPriceAt: 'New price at UTC on { date }',
      paymentDetails: 'Payment Details',
      paymentMethod: 'Payment method',
      billingAddress: 'Billing address',
      manage: 'Manage',
      change: 'Change',
      accepted: 'accepted',
      creditCardEndingIn: 'Credit card ending in',
    },
    priceChangeModal: {
      priceChange: 'Price Change',
      thisMonth: 'This month',
      afterAdjust: '{ amount } in the next month after the price adjustment',
      subtotal: 'Subtotal',
      salesTax: 'Sales tax { taxRate }',
    },
  },
  teamWarnings: {
    planExpirationReminder: 'Plan Expiration Reminder',
    planLimitReminder: 'Plan Limit Reminder',
    planDisabledReminder: 'Disabled Reminder',
    planExpiredWarning:
      "The plan of team {teamName} has expired. Subscribe to a plan to regain access to your team's features.",
    planMemberWarning:
      'The number of team members exceeds the plan limit. Please manage your number of members or upgrade your plan.',
    planStorageWarning:
      'Team storage usage exceeds the plan limit. Please manage your datasets or upgrade your plan.',
    planMemberAndStorageWarning:
      'Team storage usage and the team members exceed the plan limit. Please manage them or upgrade your plan.',
    planMemberWarningForWorker:
      'The number of team members exceeds the plan limit. Please wait for the team manager to resolve.',
    planStorageWarningForWorker:
      'Team storage usage exceeds the plan limit. Please wait for the team manager to resolve.',
    planMemberAndStorageWarningForWorker:
      'Team storage usage and the team members exceed the plan limit. Please wait for the team manager to resolve.',
    subscribeButton: 'Subscribe to a plan',
    manageMembersButton: 'Manage members',
    manageDatasetButton: 'Manage datasets',
    upgradePlanButton: 'Upgrade plan',
  },
  teamTimezone: {
    placeholder: 'Timezone',
    timezone: 'Timezone',
    required: 'Please Select Team Time Zone',
  },
};
