export default {
  forceLogoutTip: '您已经被强制下线',
  tokenChangeTip: '您的用户身份已更改，点击确定重定向到首页',
  versionTipTitle: '🎆版本已更新',
  versionTipContent: '我们的系统已更新至最新版本，请刷新页面以继续使用。谢谢。',
  api: {
    operationFailed: '操作失败',
    errorTip: '错误提示',
    errorMessage: '操作失败，系统异常',
    timeoutMessage: '登录超时，请重新登录',
    apiTimeoutMessage: '接口请求超时，请刷新页面重试',
    apiRequestFailed: '请求出错，请稍候重试',
    networkException: '网络异常',
    networkExceptionMsg: '网络异常，请检查您的网络连接是否正常！',

    errMsg401: '登录超时，请重新登录',
    errMsg403: '用户有权限，但访问受限',
    errMsg404: '网络请求错误，未找到该资源',
    errMsg405: '网络请求错误，不允许的请求方式！',
    errMsg408: '网络请求超时！',
    errMsg500: '服务器错误，请联系管理员！',
    errMsg501: '网络未实现！',
    errMsg502: '网络错误！',
    errMsg503: '服务不可用，服务器暂时过载或正在维护!',
    errMsg504: '网络超时！',
    errMsg505: 'http版本不支持该请求！',
    disbandTeamTips: '团队不存在',
    userExistTips: '你已被移出团队',
  },
  app: { logoutTip: '温馨提醒', logoutMessage: '是否确认退出系统?', menuLoading: '菜单加载中...' },
  errorLog: {
    tableTitle: '错误日志列表',
    tableColumnType: '类型',
    tableColumnDate: '时间',
    tableColumnFile: '文件',
    tableColumnMsg: '错误信息',
    tableColumnStackMsg: '堆栈信息',

    tableActionDesc: '详情',

    modalTitle: '错误详情',

    fireVueError: '触发vue错误',
    fireResourceError: '触发资源加载错误',
    fireAjaxError: '触发ajax错误',

    enableMessage: '只在`/src/settings/projectSetting.ts` 内的useErrorHandle=true时生效.',
  },
  exception: {
    backLogin: '返回登录',
    backHome: '返回首页',
    subTitle403: '抱歉，您无权访问此页面。',
    subTitle404: '抱歉，您访问的页面不存在。',
    subTitle500: '抱歉，服务器错误。',
    noDataTitle: '当前页无数据',
    networkErrorTitle: '网络错误',
    networkErrorSubTitle: '抱歉，您的网络连接已断开，请检查您的网络！',
  },
  lock: {
    unlock: '点击解锁',
    alert: '锁屏密码错误',
    backToLogin: '返回登录',
    entry: '进入系统',
    placeholder: '请输入锁屏密码或者用户密码',
  },
  login: {
    updatePwd: '修改密码',
    updatePwdTips: '为了确保您账户的安全性，请修改密码',
    confirmUpdage: '确认修改',
    jump: '跳过',
    backSignIn: '返回',
    signInFormTitle: '登录',
    signUpFormTitle: '注册',
    forgetFormTitle: '重置密码',
    joinTeamTitle: '输入团队ID',
    notAMember: '不是成员',

    signInTitle: '欢迎',
    signInDesc: '输入您的个人详细信息开始使用！',
    policy: '我同意xxx隐私政策',
    scanSign: `扫码后点击"确认"，即可完成登录`,

    backButton: '返回',
    loginButton: '登录',
    registerButton: '注册',
    resetPwdButton: '提交',
    returnButton: '返回',
    continueButton: '继续',
    joinButton: '加入',
    rememberMe: '记住我',
    forgetPassword: '忘记密码?',
    otherSignIn: '其他登录方式',

    // validate
    passwordValidationError: '密码格式错误',

    // notify
    loginSuccessTitle: '登录成功',
    loginSuccessDesc: '欢迎回来',

    // placeholder
    accountPlaceholder: '请输入用户名',
    emailPlaceholder: '请输入邮箱',
    passwordPlaceholder: '请输入密码',
    smsPlaceholder: '请输入验证码',
    mobilePlaceholder: '请输入手机号码',
    policyPlaceholder: '勾选后才能注册',
    diffPwd: '两次输入密码不一致，请重新输入',
    teamNamePlaceholder: '请输入团队名',
    joinTeamPlaceholder: '请输入团队ID',

    userName: '账号',
    password: '密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    email: '邮箱',
    teamName: '团队名',
    team: '团队',
    phoneNumber: '电话号码',
    account: '账号',

    loginTips: '没有账号?',
    signUpTips: '已有账号?',
    forgetPwdTips: '请输入您的邮箱来重置密码',
    resetPwdTips: '重置密码',
    teamIDCopiedTips: '团队ID已复制到剪切板',

    resetSuccessTitle: '密码已重置!',
    resetSuccessTips: '5秒后返回登录页',
    joinSuccessFeedDescription: '已发送加入请求。',
    joinSuccessFeedDescription2: '请联系团队管理员审批。',
    createSuccessFeedDescription: '已创建。',
    createSuccessFeedDescription2: '你的团队ID是',
    signupSuccessFeedDescription: '即将完成注册，请检查你的邮箱！',
    signupSuccessFeedDescription2: '已经同意？',
    pwdTips: '密码必须包含',
    pwdRules1: '8-64 字符',
    pwdRules2: '数字',
    pwdRules3: '字符',
    agreeToTips: '注册即代表我同意倍赛科技的',
    terms: '使用条款',
    privacyPolicy: '隐私政策',
    loginIntroduct:
      '我们致力于构建世界上最流畅的训练数据平台，帮助您的团队大规模收集、标注和部署自定义ML数据集。',
    alreadyHaveAccountError: '此电子邮件已与您的某个帐户关联，请登录或重置密码。',
    loginError: '此电子邮件已与您的帐户关联，请登录或重置密码。',
    signInWithGoogle: '谷歌登录',
    signUpTitle: '创建账号',

    loginReminderTitle: '登陆提醒',
    loginReminderContent: '该账户已经登录，重复登录会使另一方下线。是否继续登录？',
    emailResentSuccess: '邮件重发成功',
    licenseExpiredTitle: '许可证已过期',
    licenseExpiredText:
      '您的基础 AI 许可证已过期。请联系您的系统管理员并请求更新许可证以继续与我们合作。谢谢。',
    licenseExpire: {
      notice: '通知',
      expired: '您的许可证已于 {date} 到期. 请联系管理员进行续订。',
    },
    // TODO 中文
    forget: {
      forgetPassword: ' Forget password ?',
      notAMember: 'Not a member?',
      resubmitEmail:
        'This link has been used to change your password. Please resubmit your new email address',
      sendToTheEmail: 'We will send the reset password link to the following email address :',
      Oops: 'Oops!',
      wrongEmail: 'wrong email',
      resend: 'Resend',
    },
  },
  team: {
    companyName: 'Company Name',
    country: 'Country and Region',
    businessEmail: 'Business Email',
    verifyCode: 'Verify Code',
    verify: 'Verify',
    continue: 'Continue',
    manageTeams: 'Manage Teams',
    upgradeNow: 'Upgrade Now',

    businessTip:
      'Please note that each domain in the enterprise email system can only create up to 5 teams for free.',
    maxTeam:
      'You seems have reached the maximum limit of 5 teams for your enterprise email. To create more teams, please upgrade to our premium plan or delete existing teams to free up space.',
    validEmail: 'Please enter a valid email address.',
    enterpriseName: 'Please enter Enterprise email',
    verifyExpired: 'The verification code has expired. Please request a new code and try again.',
    verifyError: 'Oops! The verification code you entered is incorrect. Please try again.',
    verifySent: 'A verification code has been sent to your email,please enter the code below',
    verifyEmail1: 'Please include @ in your email address',
    verifyEmail2: 'Please enter the content before/after “{value}”',
  },
  contact: {
    hey: 'Hey there!',
    tip: "We've got a fun and friendly Slack community where you can communicate with us, share your ideas, and provide feedback. Click the button below to be redirected to our Slack channel. We'd love to have you onboard!",
    takeMeToSlack: 'Take me to Slack!',
  },
};
