export default {
  taskPerformance: '타스크 성과',
  workerPerformance: '작업자 성과',
  someonePerformance: '의 성과',
  chart: {
    day: '일',
    week: '주',
    month: '월',
  },
  export: {
    exportSettings: '도출 설정 ',
    task: '타스크',
    workers: '작업자',
    exportResultsFor: '결과 도출',
    valid: '유효 & 알 수 없음',
    invalid: '무효',
    performanceValidity: '데이터 유효성',
    exporting: '도출 중',
    exported: '도출 완성',
  },
  condition: {
    countConditions: '통계 조건',
    conditionInfo: '지난 6개월 동안 생성된 작업만 성과 분석에 지원됩니다.',
    taskHolder: '타스크 ID/타스크 이름',
    dataType: '데이터 유형',
    scenarioType: '시나리오 유형',
    linkedDataset: '연결된 데이터셋',
    annotationType: '라벨링 유형',
    taskStarted: '작업 시작',
    taskCompleted: '작업 완료',
    static: '단일 프레임',
    scene: '씬',
    dataStatus: '데이터 상태',
    completed: '완료',
    completedInfo: '작업 관리자가 데이터를 승인합니다. 승인되면 성과 통계가 정지됩니다.',
    submitted: '제출',
    submittedInfo:
      '이 데이터는 작업자가 제출하여 작업 관리자는 아직 수락하지 않았습니다. 이런 경우에 성과 통계는 작업이 진행됨에 따라 변경될 수 있습니다.',
    dataValidity: '데이터 유효',
    valid: '유효',
    invalid: '무효',
    validityInfo: '데이터가 작업에서 유효 또는 무효인지 표시 여부',
    date: '날짜',
    day: '일',
    week: '주',
    month: '월',
    thisWeek: '이번 주',
    thisMonth: '이번 달',
    // TODO
    byDay: 'By Day',
    byWeek: 'By Week',
    byMonth: 'By Month',
    upToNow: '현재까지',
    upTtoYesterday: '어제까지',
    completedAt: '완료 시간',
    submittedAt: '제출 시간',
    last7Days: '지난 7일',
    last30Days: '지난 30일',
    last90Days: '지난 90일',
    last180Days: '지난 180일',
  },
  taskData: {
    dataPerformance: '데이터 성과',
    data: {
      completedData: '완료된 데이터',
      submittedData: '제출된 데이터',
      items: '아이템',
      scenes: '씬',
      frames: '프레임',
      completedInfo: {
        framesInfo: '필터링된 기간 동안 검수된 씬/프레임 수입니다.',
        singleInfo: '필터링된 기간 동안 검수된 데이터 수입니다.',
      },
      submittedInfo: {
        framesInfo: '필터링된 기간 동안 제출된 씬/프레임 수입니다.',
        singleInfo: '필터링된 기간 동안 제출된 데이터 수입니다.',
      },
    },
    valid: {
      validWorkDuration: '유효한 작업 기간',
      stageBreakdown: '단계 정보',
      total: '합계',
      averageScene: '평균/씬',
      average: '평균',
      completedInfo: {
        total: '합계: 모든 단계에서 작업 완성시키는 총 작업 기간',
        framesAverage:
          '평균/씬 = 총 작업 기간/ 씬 수. 어느 한 씬을 작업 완성시키는 평균 작업 기간.',
        singleAverage:
          '평균 = 총 작업 기간/ 데이터 수. 어느 한 데이터를 작업 완성시키는 평균 작업 기간.',
      },
      submittedInfo: {
        total: '합계: 총 작업 기간',
        framesAverage: '평균/ 씬 = 총 작업 기간/ 씬 수. 어느 한 씬의 평균 작업 기간.',
        singleAverage: '평균 = 총 작업 기간/ 데이터 수. 어느 한 데이터의 평균 작업 기간.',
      },
    },
    quality: {
      quality: '품질',
      accuracy: '정확도',
      passRate: '통과율',
      AccAccuracy: 'ACC 정확도',
      AccPassRate: 'ACC 통과율',
      completedInfo: {
        accuracy: '정확도: ACC 단계의 총 부정확한 데이터 수/ 총 데이터 수.',
        passRate: '통과율: [FIXME]',
        AccAccuracy: 'ACC 정확도: ACC 단계의 총 부정확한 데이터 수/ 총 데이터 수.',
        AccPassRate: 'ACC 통과율: [FIXME]',
      },
      submittedInfo: {
        accuracy: '정확도: 총 부정확한 데이터 수/총 데이터 수.',
        passRate: ' 통과율: [FIXME]',
        AccAccuracy: 'ACC 정확도: 총 부정확한 데이터 수/총 데이터 수.',
        AccPassRate: 'ACC 통과율: [FIXME]',
      },
      gatherInfo: '전 타스크의 평균입니다.',
      // TODO
      d: 'D',
      h: 'H',
      m: 'M',
      s: 'S',
    },
    redo: {
      redo: '재작업',
      rejectedData: '반려',
      resetData: '리셋',
      redoScenes: '재작업 씬',
      resetScenes: '리셋 씬',
      redoItems: '재작업 아니템',
      resetItems: '리셋 아니템',
      completedInfo: {
        frames: {
          redoScenes: '재작업 씬: 반려된 씬 수/ACC 단계에서 이전 단계로 재할당된 씬 수.',
          resetScenes:
            '리셋 씬: 반려된 씬 수/ 재할당되어 ACC 단계의 초기 단계에서 결과가 지워진 씬 수',
        },
        single: {
          redoItems:
            '재작업 아니템: 반려된 아니템 수/ ACC 단계에서 이전 단계로 재할당된 아니템 수.',
          resetItems:
            '리셋 아니템: 반려된 아니템 수/ 재할당되어 ACC 단계의 초기 단계에서 결과가 지워진 아니템 수',
        },
      },
      submittedInfo: {
        frames: {
          redoScenes: '재작업 씬: 반려된 씬 수/이전 단계로 재할당된 씬 수.',
          resetScenes: '리셋 씬: 반려된 씬 수/ 재할당되어 이전 단계에서 결과가 지워진 씬 수.',
        },
        single: {
          redoItems: '재작업 아니템: 반려된 아니템 수/ 이전 단계로 재할당된 아니템 수.',
          resetItems:
            '리셋 아니템: 반려된 아니템 수/ 재할당되어 이전 단계에서 결과가 지워진 아니템 수.',
        },
      },
    },
  },
  taskObject: {
    objectPerformance: '객체 성과',
    objectCount: '객체 카운트',
    viewBy: '보기 기준',
    object: '객체',
    class: '클래스',
    filterObjectType: '객체 유형 필터',
    create: '생성',
    createInfo: '생성: 새 객체 수',
    viewImported: '도출 보기',
    viewInfo: '도출 보기: 전 처리된 겍체 수',
    edit: '편집',
    editInfo: '편집: 편집된 객체 수',
    delete: '삭제',
    deleteInfo: '삭제: 삭제된 객체 수',
    review: '리뷰',
    reviewInfo: '리뷰: 리뷰된 객체 수',
    accept: '검수',
    acceptInfo: '검수: 검수된 객체 수',
    // TODO
    sum: 'Sum',
    total: '합계',
    filterClass: '필터 클래스',
    pleaseSelect: '선택하세요...',
  },
  taskAccuracy: {
    pointAccuracy: '포인트 정확률',
    objectAccuracy: '객체 정확도',
    ACCObjectAccuracy: 'ACC 객체 정확도',
    ACCAccuracy: 'ACC 정확도',
    DataAccuracyInfo: 'ACC 단계의 총 정확한 데이터 수/총 데이터 수.',
    instanceObjectAccuracyInfoForAdminCompleteAnnotate:
      '1 - ACC 단계의 잘못된 객체 수/ 생성된 총 객체 수.',
    instanceObjectAccuracyInfoForCompleteReview: '1 - 잘못된 객체 수/ 리뷰된 총 객체 수.',
    instanceObjectAccuracyInfoForWorkerCompleteAnnotate: '1 - 잘못된 객체 수/ 생성된 총 객체 수.',
    segmentationDataAccuracyInfoForWorker: '총 정확한 데이터 수/총 데이터 수.',
    segmentationObjectAccuracyInfoForAdmin: '1 - ACC 단계의 잘못된 포인트 수/ 작업된 총 포인트 수.',
    segmentationObjectAccuracyInfoForWorkerAnnotate: '1 - 잘못된 포인트 수/ 작업된 총 포인트 수.',
    segmentationObjectAccuracyInfoForWorkerReview: '1 - 잘못된 포인트 수/ 리뷰된 총 포인트 수.',
    instanceTitle: '인스턴스 (Seg. 제외)',
    // TODO 韩文
    pointAccuracyAnnotate: 'Point Accuracy - Annotate',
    pointAccuracyReview: 'Point Accuracy - Review',
    image: {
      segmentationDataAccuracy: {
        complete: 'Total Number of Accurate Data in ACC stage/ Total Number of Data.',
        annotationStage: 'Total Number of Accurate Data/ Total Number of Data.',
        reviewStage: 'Total Number of Accurate Data/ Total Number of Data.',
      },
      segmentationObjectAccuracy: {
        complete: '1 - Number of Wrong Objects in ACC/ Total Number of Created Objects.',
        annotationStage: '1 - Number of Wrong Objects/ Total Number of Created Objects.',
        reviewStage: '1 - Number of Wrong Objects/ Total Number of Reviewed Objects.',
      },
    },
  },
  tableList: {
    columns: '열',
    type: '유형',
    // TODO
    sum: 'Sum',
    object3D: '3D 객체',
    noClass: '클래스 없음',
    box3D: '3D 큐보이드',
    box2D: '2D 큐보이드',
    rect2D: '2D 박스',
    rectangle: '직사각형',
    polygon: '폴리곤',
    polyline: '폴리라인',
    polygon2D: '2D폴리곤',
    polyline2D: '2D폴리라인',
    polygon3D: '3D폴리곤',
    polyline3D: '3D폴리라인',
    imageCuboid: '큐보이드',
    total: '합계',
    name: '이름',
    completedScenes: '완료된 씬',
    submittedScenes: '제출된 씬',
    scenesInfo: '필터링된 기간 동안 검수된 씬 수입니다.',
    completedItems: '완료된 아이템',
    submittedItems: '제출된 아이템',
    itemsInfo: '필터링된 기간 동안 검수된 데이터 수입니다.',
    completedFrames: '완료된 프래임',
    submittedFrames: '제출된 프래임',
    framesInfo: '필터링된 기간 동안 검수된 프래임 수입니다.',
    totalDuration: '총 기간',
    totalDurations: '총 기간(s)',
    totalInfo: '$stageName 단계의 총 작업 기간.',
    averageDuration: '평균 기간',
    averageDurationUnit: '평균 기간 (s)',
    averageDurationScene: '평균 기간/씬 (s)',
    averageScenesInfo:
      '총 작업 기간/ 씬 수. $stageName 단계에서 씬(scene)을 완료하는 데 걸리는 평균 작업 기간입니다.',
    averageItemsInfo: '총 작업 기간/ 데이터 수. 데이터를 완료하는 데 걸리는 평균 작업 기간입니다.',
    passRate: '통과율',
    // TODO
    passInfo: '[FIXME]',
    rejectedScenes: '반려된 씬',
    rejectScenesInfo: '반려된 씬 수/ 다른 작업자에게 재할당된 씬 수.',
    rejectedItems: '반려된 아이템',
    rejectItemsInfo: '반려된 아이템 수/ 다른 작업자에게 재할당된 씬 수.',
    resetScenes: '리셋 씬',
    resetScenesInfo: '반려된 씬 수/ 다른 작업자에게 재할당되어 결과가 지워진 씬 수.',
    resetItems: '리셋 아이템',
    resetItemsInfo:
      '리셋 아이템: 반려된 아이템 수/ 재할당되어 ACC 단계의 이전 단계로 결과가 지워진 아이템 수.',
    objectPerformance: '객체 성과',
    annotation: {
      createInfo: '생성: 작업자가 생성된 새 객체 수',
      viewInfo: '도출 보기: 작업자가 본 전 처리된 객체 수',
      editInfo: '편집: 다른 사용자가 생성하고 작업자가 편집한 객체 수',
      deleteInfo: '삭제: 다른 사용자가 생성하고 작업자가 삭제한 객체 수',
    },
    review: {
      reviewInfo: '리뷰: 작업자가 리뷰한 객체 수',
      createInfo: '생성: 작업자가 생성된 새 객체 수',
      editInfo: '편집: 다른 사용자가 생성하고 작업자가 편집한 객체 수',
      deleteInfo: '삭제: 다른 사용자가 생성하고 작업자가 삭제한 객체 수',
    },
    acceptance: {
      acceptInfo: '검수: 작업자가 검수한 객체 수',
      createInfo: '생성: 작업자가 생성된 새 객체 수',
      editInfo: '편집: 다른 사용자가 생성하고 작업자가 편집한 객체 수',
      deleteInfo: '삭제: 다른 사용자가 생성하고 작업자가 삭제한 객체 수',
    },
    objectAccuracy: '객체 정확도',
    accuracyInfo: {
      createInfo: '생성: 1 - 코멘트 수/ 생성한 객체 수',
      reviewInfo: '리뷰: 1 - 코멘트 수/ 리뷰된 객체 수',
    },
    segAccuracy: 'Seg.정확도',
  },
};
